version: "3.0"

services:
  demo-mongo:
    image: mongo:4.4
  demo-postgres:
    environment:
      POSTGRES_HOST_AUTH_METHOD: trust
    image: postgres:14.2
  jupyter:
    depends_on:
      - demo-mongo
      - demo-postgres
    image: jupyter/base-notebook:notebook-6.4.11
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
